"""empty message

Revision ID: 7cc7b0b81fa4
Revises: 4452ceacb644
Create Date: 2017-11-30 10:41:52.921142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc7b0b81fa4'
down_revision = '4452ceacb644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CharaValue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DeviceID', sa.Integer(), nullable=False),
    sa.Column('data1_maxValue', sa.Float(), nullable=True),
    sa.Column('data1_meanValue', sa.Float(), nullable=True),
    sa.Column('data2_maxValue', sa.Float(), nullable=True),
    sa.Column('data2_meanValue', sa.Float(), nullable=True),
    sa.Column('data3_maxValue', sa.Float(), nullable=True),
    sa.Column('data3_meanValue', sa.Float(), nullable=True),
    sa.Column('data4_maxValue', sa.Float(), nullable=True),
    sa.Column('data4_meanValue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InstWheel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceid', sa.Integer(), nullable=False),
    sa.Column('package', sa.Integer(), nullable=True),
    sa.Column('data1', sa.Float(), nullable=True),
    sa.Column('data2', sa.Float(), nullable=True),
    sa.Column('data3', sa.Float(), nullable=True),
    sa.Column('data4', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('InstWheel')
    op.drop_table('CharaValue')
    # ### end Alembic commands ###
