"""empty message

Revision ID: d289f6ee377c
Revises: 
Create Date: 2018-12-18 23:48:05.596962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd289f6ee377c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CharaValue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DeviceID', sa.Integer(), nullable=False),
    sa.Column('data1_maxValue', sa.Float(), nullable=True),
    sa.Column('data1_meanValue', sa.Float(), nullable=True),
    sa.Column('data2_maxValue', sa.Float(), nullable=True),
    sa.Column('data2_meanValue', sa.Float(), nullable=True),
    sa.Column('data3_maxValue', sa.Float(), nullable=True),
    sa.Column('data3_meanValue', sa.Float(), nullable=True),
    sa.Column('data4_maxValue', sa.Float(), nullable=True),
    sa.Column('data4_meanValue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InstWheel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceid', sa.Integer(), nullable=False),
    sa.Column('package', sa.Integer(), nullable=True),
    sa.Column('data1', sa.Float(), nullable=True),
    sa.Column('data2', sa.Float(), nullable=True),
    sa.Column('data3', sa.Float(), nullable=True),
    sa.Column('data4', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('InstWheel')
    op.drop_table('CharaValue')
    # ### end Alembic commands ###
