"""empty message

Revision ID: f6f6d4c1397e
Revises: 
Create Date: 2017-11-30 09:42:45.546389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6f6d4c1397e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('CharaValue')
    op.drop_table('InstWheel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InstWheel',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('data1', mysql.FLOAT(), nullable=True),
    sa.Column('data2', mysql.FLOAT(), nullable=True),
    sa.Column('data3', mysql.FLOAT(), nullable=True),
    sa.Column('data4', mysql.FLOAT(), nullable=True),
    sa.Column('deviceid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('package', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('CharaValue',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('DeviceID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data1_maxValue', mysql.FLOAT(), nullable=True),
    sa.Column('data1_meanValue', mysql.FLOAT(), nullable=True),
    sa.Column('data2_maxValue', mysql.FLOAT(), nullable=True),
    sa.Column('data2_meanValue', mysql.FLOAT(), nullable=True),
    sa.Column('data3_maxValue', mysql.FLOAT(), nullable=True),
    sa.Column('data3_meanValue', mysql.FLOAT(), nullable=True),
    sa.Column('data4_maxValue', mysql.FLOAT(), nullable=True),
    sa.Column('data4_meanValue', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
